"""empty message

Revision ID: a0c6e15c082f
Revises: f102eba041a4
Create Date: 2016-07-25 23:07:22.232611

"""

# revision identifiers, used by Alembic.
revision = 'a0c6e15c082f'
down_revision = 'f102eba041a4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('attachments', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'attachments')
    ### end Alembic commands ###
