"""empty message

Revision ID: f102eba041a4
Revises: e5adf24f2bf5
Create Date: 2016-07-09 21:06:04.057304

"""

# revision identifiers, used by Alembic.
revision = 'f102eba041a4'
down_revision = 'e5adf24f2bf5'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addressee',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('val', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_addressee_val'), 'addressee', ['val'], unique=True)
    op.create_table('attachment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('path', sa.String(length=255), nullable=False),
                    sa.Column('email_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('emails_addressees',
                    sa.Column('email_id', sa.Integer(), nullable=True),
                    sa.Column('addressee_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['addressee_id'], ['addressee.id'], ),
                    sa.ForeignKeyConstraint(['email_id'], ['email.id'], )
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    op.drop_table('emails_addressees')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_addressee_val'), table_name='addressee')
    op.drop_table('addressee')
    ### end Alembic commands ###
