"""empty message

Revision ID: f102eba041a4
Revises: e5adf24f2bf5
Create Date: 2016-07-09 21:06:04.057304

"""

# revision identifiers, used by Alembic.
revision = 'f102eba041a4'
down_revision = 'e5adf24f2bf5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('to', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    ### end Alembic commands ###
