CONTAINER_CLIENT_PACKAGES = 'compressedpackages'
CONTAINER_EMAILS = 'emails'
CONTAINER_SENDGRID_MIME = 'sendgridinboundemails'
TABLE_DOMAIN_X_DELIVERED = 'emaildomainxdelivered'
TABLE_AUTH = 'clientsauth'
QUEUE_CLIENT_PACKAGE = 'lokoleinboundemails'
QUEUE_EMAIL_SEND = 'sengridoutboundemails'
QUEUE_SENDGRID_MIME = 'sengridinboundemails'
