UNREGISTERED_CLIENT = 'unregistered_client'
EMAILS_DELIVERED_TO_CLIENT = 'emails_delivered_to_client'
EMAILS_RECEIVED_FROM_CLIENT = 'emails_received_from_client'
EMAIL_RECEIVED_FOR_CLIENT = 'email_received_for_client'
EMAIL_DELIVERED_FROM_CLIENT = 'email_delivered_from_client'
EMAIL_STORED_FOR_CLIENT = 'email_stored_for_client'
EMAIL_STORED_FROM_CLIENT = 'email_stored_from_client'
