name: CD

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make github-env
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          make \
            -e BUILD_TARGET=runtime \
            -e DOCKER_TAG="${GITHUB_REF##*/}" \
            -e DOCKER_BUILD_ARGS="--no-cache" \
            release-docker deploy-docker release-pypi deploy-pypi
